function plotSampleHeadAngSpeedTraj(headAngSpeedRanges,wormcats,numSampleTraj,strain,wormnum)

% function takes saved sample traj data in microns (generated by plotHeadAngSpeed.m), category of worms to analysis,
% strain name, plus desired number of sample trajectories, and plots/saves
% figures of worm trajectories

%% INPUTS
% headAngSpeedRanges: struct containing fields matching entries in wormcat. Each field contains 500x2x5 cell array for 500 trajectories, xy
% coordinates, and 5 sampling ranges.
% wormcat: cell array containing categories of worms to be analysed.
% Usually {'leaveCluster','loneWorm').
% strain: string specifying the strain to be analysed.
% numSampleTraj: [1x1] double specifying the number of trajectories to be
% plotted for each sample onto the same graph
%% OUTPUT
% trajectory plots

%% function
% import saved traj values
headAngSpeedSampleTraj = importdata(['figures/turns/results/headAngSpeedSampleTraj_' strain '_' wormnum '.mat']);
for rangeCtr = 1:size(headAngSpeedRanges,1)
    for wormcatCtr = 1:length(wormcats)
        samplePathFig = figure; hold on
        % remove empty cells
        headAngSpeedSampleTrajRange = squeeze(headAngSpeedSampleTraj.(wormcats{wormcatCtr})(:,:,rangeCtr));
        headAngSpeedSampleTrajRange =  headAngSpeedSampleTrajRange(~cellfun('isempty',headAngSpeedSampleTrajRange));
        headAngSpeedSampleTrajRange = reshape(headAngSpeedSampleTrajRange,[],2);
        % randomly sample 10 trajectories from the 500 saved ones
        trajSamples = randi(size(headAngSpeedSampleTrajRange,1),[numSampleTraj,1]);
        % loop through each saved trajectory xy coordinates
        for trajCtr = 1:length(trajSamples)
            % get xy coordinates for sample traj
            traj_xcoords = headAngSpeedSampleTraj.(wormcats{wormcatCtr}){trajSamples(trajCtr),1,rangeCtr};
            traj_ycoords = headAngSpeedSampleTraj.(wormcats{wormcatCtr}){trajSamples(trajCtr),2,rangeCtr};
            % set all trajectories to start at 0,0
            traj_xcoords = traj_xcoords - traj_xcoords(1);
            traj_ycoords = traj_ycoords - traj_ycoords(1);
            % plot
            set(0,'CurrentFigure',samplePathFig)
            plot(traj_xcoords,traj_ycoords)
            %waitforbuttonpress
        end
        % format and save plot
        title([strain '\_' wormcats{wormcatCtr} ' sampleTraj, '...
            num2str(headAngSpeedRanges(rangeCtr,1)) '-' num2str(headAngSpeedRanges(rangeCtr,2)) '°/s'],'FontWeight','normal')
        set(samplePathFig,'PaperUnits','centimeters')
        xlim([-250 250])
        ylim([-250 250])
        xlabel('microns');
        ylabel('microns');
        ax = gca;
        ax.XAxisLocation = 'origin';
        ax.YAxisLocation = 'origin';
        figurename = ['figures/turns/sampleTraj/' strain '_' wormnum '_' wormcats{wormcatCtr} '_range' num2str(rangeCtr)];
        %savefig(samplePathFig,[figurename '.fig'])
        load('exportOptions.mat')
        %exportfig(samplePathFig,[figurename '.eps'],exportOptions)
        %system(['epstopdf ' figurename '.eps']);
        %system(['rm ' figurename '.eps']);
    end
end